# This file is managed by the repo-content-updater project. Manual changes here will result in a PR to bring back
# inline with the upstream template, unless you remove the dependabot managed file property from the repo

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 30
    rebase-strategy: auto
    labels:
      - dependencies
      - github_actions
      - "Changed"
    commit-message:
      prefix: 'github-actions'
      include: scope
    reviewers: 
      - wallentx

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 30
    commit-message:
      prefix: 'pnpm'
      include: scope
    versioning-strategy: 'increase'
    rebase-strategy: auto
    labels:
      - dependencies
      - javascript
      - "Changed"
    reviewers: 
      - wallentx
